# Deploy a STAC Browser website to github pages
name: STAC Browser

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout STAC Browser Source
      uses: actions/checkout@v2
      with:
        repository: radiantearth/stac-browser
        path: stac-browser

    - name: Install STAC Browser
      run: |
        npm install .
        pwd
        ls

    - name: Checkout STAC Repo
      uses: actions/checkout@v2

    - name: Build Website
      run: |
        npm run --prefix ../stac-browser build -- --CATALOG_URL="collection.json"
        tree ../stac-browser/dist

    # - name: Publish to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     personal_token: ${{ secrets.GH_PAT }}
    #     publish_dir: ../stac-browser/dist/
    #     publish_branch: gh-pages
